[package]
name = "psxdemos"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hello-world"

[[bin]]
name = "simple-graphics"

[[bin]]
name = "textured-graphics"

[dependencies]
psx = { path = "./psx-sdk-rs/psx" }
